// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Returns the signed-in user's email and id \u2014 useful to verify the MCP connection is authenticated.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    return {
      content: [{
        type: "text",
        text: `Signed in as ${ctx.getUserEmail() ?? "(no email)"} (${ctx.getUserId()})`
      }]
    };
  }
});

// src/lib/mcp/tools/list-my-assessments.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_assessments_default = defineTool2({
  name: "list_my_assessments",
  title: "List my assessments",
  description: "Lists AI Tools Assessments submitted from the signed-in user's email address.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No email on token" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("assessments").select("id, company, contact_name, status, created_at, delivered_at").eq("email", email).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { assessments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-assessment-report.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_assessment_report_default = defineTool3({
  name: "get_assessment_report",
  title: "Get assessment report",
  description: "Returns the full AI Tools Assessment report for a given assessment id. Only returns the report if the assessment belongs to the signed-in user's email.",
  inputSchema: {
    id: z.string().describe("Assessment id (UUID).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No email on token" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("assessments").select("id, company, contact_name, email, status, report, created_at").eq("id", id).eq("email", email).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Not found or not yours" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { assessment: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ulvqqtubrrkhoodxtqhu";
var mcp_default = defineMcp({
  name: "ccg-app-mcp",
  title: "Cooman Consulting Group",
  version: "0.1.0",
  instructions: "Tools for Cooman Consulting Group. Use `whoami` to verify the connection, `list_my_assessments` to list AI Tools Assessments tied to the signed-in user's email, and `get_assessment_report` to fetch the full report for a specific assessment.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_assessments_default, get_assessment_report_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
